#!/usr/bin/env bash
#
# Vendor the upstream skills declared in upstreams.json into plugin/skills/,
# patch them (frontmatter + path rewrites), refresh license attribution, and
# regenerate NOTICE + VENDOR.lock.
#
# This script is GENERIC: it iterates over upstreams.json and contains no
# skill-specific logic. To add / swap / remove a bundled skill, edit
# upstreams.json and re-run. Idempotent.
#
# Usage:
#   scripts/sync-upstreams.sh          # vendor + patch, leave versions as-is
#   scripts/sync-upstreams.sh --bump   # also bump the plugin patch version
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT/upstreams.json"
SKILLS_DIR="$ROOT/plugin/skills"
THIRD="$ROOT/third_party"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

BUMP=0
[ "${1:-}" = "--bump" ] && BUMP=1

command -v git >/dev/null      || { echo "git required"; exit 1; }
command -v python3 >/dev/null  || { echo "python3 required"; exit 1; }

echo "==> Reading manifest: $MANIFEST"
python3 - "$MANIFEST" > "$TMP/rows.tsv" <<'PY'
import json, sys
m = json.load(open(sys.argv[1], encoding="utf-8"))
for s in m["skills"]:
    print("\t".join([s["name"], s["repo"], s["ref"], s["sourceSubpath"],
                     s["target"], s.get("licenseFile", "LICENSE")]))
PY

mkdir -p "$SKILLS_DIR" "$THIRD"
: > "$TMP/resolved.tsv"

while IFS=$'\t' read -r name repo ref subpath target licfile; do
  [ -n "$name" ] || continue
  echo "==> $name  ($repo @ $ref)"
  clone="$TMP/clone-$name"
  if printf '%s' "$ref" | grep -Eq '^[0-9a-f]{40}$'; then
    # pinned by commit SHA (no tag available upstream)
    git init -q "$clone"
    git -C "$clone" remote add origin "$repo"
    git -C "$clone" fetch -q --depth 1 origin "$ref"
    git -C "$clone" checkout -q FETCH_HEAD
  else
    # pinned by tag or branch
    git clone -q --depth 1 --branch "$ref" "$repo" "$clone"
  fi
  resolved="$(git -C "$clone" rev-parse HEAD)"

  src="$clone/$subpath"
  [ -d "$src" ] || { echo "ERROR: source subpath '$subpath' not found in $name"; exit 1; }
  dest="$SKILLS_DIR/$target"
  rm -rf "$dest"; mkdir -p "$dest"
  cp -R "$src/." "$dest/"

  mkdir -p "$THIRD/$target"
  [ -f "$clone/$licfile" ] && cp "$clone/$licfile" "$THIRD/$target/LICENSE" \
    || echo "  ! warning: license file '$licfile' not found for $name"
  [ -f "$clone/NOTICE" ] && cp "$clone/NOTICE" "$THIRD/$target/NOTICE" || true

  printf '%s\t%s\t%s\n' "$name" "$ref" "$resolved" >> "$TMP/resolved.tsv"
  echo "  vendored -> plugin/skills/$target  (sha ${resolved:0:10})"
done < "$TMP/rows.tsv"

echo "==> Patching vendored skills (frontmatter + path rewrites)"
python3 "$ROOT/scripts/patch-frontmatter.py" --manifest "$MANIFEST" --skills-dir "$SKILLS_DIR"

echo "==> Regenerating NOTICE + VENDOR.lock"
python3 - "$MANIFEST" "$TMP/resolved.tsv" "$ROOT/NOTICE" "$ROOT/VENDOR.lock" <<'PY'
import json, sys
manifest, resolved_path, notice_path, lock_path = sys.argv[1:5]
m = json.load(open(manifest, encoding="utf-8"))
resolved = {}
for line in open(resolved_path, encoding="utf-8"):
    parts = line.rstrip("\n").split("\t")
    if len(parts) == 3:
        resolved[parts[0]] = (parts[1], parts[2])

notice = []
notice.append("website-builder — bundled third-party skills")
notice.append("=" * 46)
notice.append("")
notice.append("This plugin vendors the skills below. Each retains its own license;")
notice.append("full copies live in third_party/<name>/.")
notice.append("")
lock = ["# Resolved upstream pins — regenerated by scripts/sync-upstreams.sh", ""]
for s in m["skills"]:
    ref, sha = resolved.get(s["name"], (s.get("ref", "?"), "?"))
    notice.append(f"- {s['name']} — {s['license']} — {s['repo']} @ {ref} (sha {sha[:10]})")
    lock.append(f"{s['name']}\t{s['repo']}\t{ref}\t{sha}")
notice.append("")
notice.append("Apache-2.0 components (impeccable): see third_party/impeccable/LICENSE")
notice.append("(and NOTICE, if present) per Apache-2.0 section 4.")
notice.append("\nGenerated by scripts/sync-upstreams.sh.")
open(notice_path, "w", encoding="utf-8").write("\n".join(notice) + "\n")
open(lock_path, "w", encoding="utf-8").write("\n".join(lock) + "\n")
PY

if [ "$BUMP" = "1" ]; then
  echo "==> Bumping plugin patch version"
  python3 - "$ROOT/plugin/.claude-plugin/plugin.json" "$ROOT/.claude-plugin/marketplace.json" <<'PY'
import json, sys
def bump(path, key_path):
    obj = json.load(open(path, encoding="utf-8"))
    node = obj
    for k in key_path[:-1]:
        node = node[k]
    cur = node[key_path[-1]]
    a, b, c = (cur.split(".") + ["0", "0", "0"])[:3]
    node[key_path[-1]] = f"{a}.{b}.{int(c)+1}"
    json.dump(obj, open(path, "w", encoding="utf-8"), indent=2)
    open(path, "a").write("\n")
    return cur, node[key_path[-1]]
old, new = bump(sys.argv[1], ["version"])
bump(sys.argv[2], ["version"])
# keep marketplace plugin-entry version in sync
mp = json.load(open(sys.argv[2], encoding="utf-8"))
for p in mp.get("plugins", []):
    if p.get("name") == "website-builder":
        p["version"] = new
json.dump(mp, open(sys.argv[2], "w", encoding="utf-8"), indent=2)
open(sys.argv[2], "a").write("\n")
print(f"  version {old} -> {new}")
PY
fi

echo "==> Done. Review with: git diff --stat"
